# http://travis-ci.org/#!/shedskin/shedskin
language: python
python:
    - 2.7
addons:
    apt:
        packages:
            - libgc-dev
cache:
    - ccache
    - pip
env:
    - OMP_NUM_THREADS=4
script:
    - cd tests && ./run.py -e && cd ..
    - cd tests && ./run.py -p && cd ..
    - cd tests && ./run.py -x && cd ..
notifications:
    email: false
