# http://travis-ci.org/#!/shedskin/shedskin
language: python
python:
    - 2.7
before_install:
    - sudo apt-get install libgc-dev
cache: ccache
env:
    - OMP_NUM_THREADS=4
script:
    - cd tests && ./run.py -p
notifications:
    email: false
